/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-01-11 01:57:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import novNara.*;

public final class memberInsert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/member/../bottom.jsp", Long.valueOf(1641783070000L));
    _jspx_dependants.put("/member/../top.jsp", Long.valueOf(1641861908000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("novNara");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
request.setCharacterEncoding("UTF-8");
      out.write('\r');
      out.write('\n');
      novNara.MemberBean mBean = null;
      mBean = (novNara.MemberBean) _jspx_page_context.getAttribute("mBean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mBean == null){
        mBean = new novNara.MemberBean();
        _jspx_page_context.setAttribute("mBean", mBean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("mBean"), request);
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>회원가입 확인</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/style.css\" />\r\n");
      out.write("<script src=\"script.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("	<br>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write('\r');
      out.write('\n');

	String id = (String)session.getAttribute("idKey");
	
	String log="";
	if(id == null) log ="<a href=../login/login.jsp>로그인</a>";
	else log = "<a href=../login/logout.jsp>로그아웃</a>";

	String reg="";
	if(id == null) reg ="<a href=../member/member.jsp>회원가입</a>";
	else reg = "<a href=../member/memberUpdate.jsp>회원수정</a>";

      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"member-buttons\">\r\n");
      out.write("        <button class=\"login\" >");
      out.print(log );
      out.write("</button>\r\n");
      out.write("        <button class=\"sign-up\" >");
      out.print(reg);
      out.write("</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav class=\"giant-box\">\r\n");
      out.write("        <div class=\"oatmeal-box\">\r\n");
      out.write("            <div class=\"nav-icons\">\r\n");
      out.write("                <i class=\"fas fa-search fa-lg\"></i>\r\n");
      out.write("                <i class=\"fas fa-shopping-basket fa-lg\"><a href=\"../cart/cartList.jsp\"></a></i>\r\n");
      out.write("\r\n");
      out.write("                <label class=\"list\" for=\"list\"> <i class=\"fas fa-bars fa-lg\" ></i></label>\r\n");
      out.write("	                <input id=\"list\" type=\"checkbox\">\r\n");
      out.write("	                <nav id=\"main_nav\">\r\n");
      out.write("	                	<ul>\r\n");
      out.write("	                		<li><a href=\"../product/productList.jsp\">전체상품</a></li>\r\n");
      out.write("    						<li><a href=\"../cart/cartList.jsp\">장바구니</a></li>\r\n");
      out.write("    						<li><a href=\"../order/orderList.jsp\">구매목록</a></li>\r\n");
      out.write("    						<li><a href=\"#\">마이페이지</a></li>\r\n");
      out.write("	                	</ul>\r\n");
      out.write("	                </nav>\r\n");
      out.write("                \r\n");
      out.write("            </div>  \r\n");
      out.write("            <div class=\"logo-box\">\r\n");
      out.write("                <img src=\"../img/logo2.png\" class=\"logo2\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"menu\">\r\n");
      out.write("                <span class=\"home\" ><a href=\"../index.jsp\">홈</a></span>\r\n");
      out.write("                <span class=\"best\"><a href=\"../product/best.jsp\" >베스트</a></span>\r\n");
      out.write("                <span class=\"product\"><a href=\"../product/productList.jsp\" >전체상품</a></span>\r\n");
      out.write("                <span class=\"objet\"><a href=\"../product/objet.jsp\" >소품</a></span>\r\n");
      out.write("                <span class=\"light\"><a href=\"../product/light.jsp\" >조명</a></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"search-box\">\r\n");
      out.write("                <div class=\"search\">\r\n");
      out.write("                    <i class=\"fas fa-search fa-2x\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <script\r\n");
      out.write("    src=\"https://kit.fontawesome.com/6478f529f2.js\"\r\n");
      out.write("    crossorigin=\"anonymous\"\r\n");
      out.write("  ></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<table width=\"95%\" align=\"center\" >\r\n");
      out.write("					<form name=\"regForm\" method=\"post\" action=\"memberProc.jsp\">\r\n");
      out.write("						<tr align=\"center\" >\r\n");
      out.write("							<td colspan=\"3\"><b> ");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((novNara.MemberBean)_jspx_page_context.findAttribute("mBean")).getId())));
      out.write(" 회원님이 작성하신 내용입니다. 다시 한번 확인해주십시오\r\n");
      out.write("								</b></font></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>아이디</td>\r\n");
      out.write("							<td><input name=\"id\"\r\n");
      out.write("								value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((novNara.MemberBean)_jspx_page_context.findAttribute("mBean")).getId())));
      out.write("\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>패스워드</td>\r\n");
      out.write("							<td><input name=\"pwd\"\r\n");
      out.write("								value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((novNara.MemberBean)_jspx_page_context.findAttribute("mBean")).getPwd())));
      out.write("\"></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>이메일</td>\r\n");
      out.write("						<td><input name=\"email\" size=\"30\"\r\n");
      out.write("							value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((novNara.MemberBean)_jspx_page_context.findAttribute("mBean")).getEmail())));
      out.write("\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"2\" align=\"center\"><input type=\"submit\"\r\n");
      out.write("							value=\"확인완료\"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <input\r\n");
      out.write("							type=\"button\" value=\"다시쓰기\" onClick=\"history.back()\"></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					</form>\r\n");
      out.write("				</table>\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
